groups:
  - name: network-alerts
    interval: 30s
    rules:
      - alert: NautobotDown
        expr: 'up{job="nautobot"} == 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Nautobot is down"
          description: "Nautobot has been down for more than 5 minutes."
          
      - alert: NodeExporterDown
        expr: 'up{job="node-exporter"} == 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter is down"
          description: "Node Exporter has been down for more than 5 minutes."
          
      - alert: PrometheusDown
        expr: 'up{job="prometheus"} == 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Prometheus is down"
          description: "Prometheus has been down for more than 5 minutes."
          
      - alert: GrafanaDown
        expr: 'up{job="grafana"} == 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Grafana is down"
          description: "Grafana has been down for more than 5 minutes."
          
      - alert: LokiDown
        expr: 'up{job="loki"} == 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Loki is down"
          description: "Loki has been down for more than 5 minutes."
          
      - alert: TelegrafDown
        expr: 'up{job="telegraf"} == 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Telegraf is down"
          description: "Telegraf has been down for more than 5 minutes."
          
  - name: resource-alerts
    interval: 1m
    rules:
      - alert: HighCPULoad
        expr: '100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80'
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU load"
          description: "CPU load is above 80% for more than 10 minutes."
          
      - alert: HighMemoryUsage
        expr: '(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85'
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 85% for more than 10 minutes."
          
  - name: telegraf-alerts
    interval: 1m
    rules:
      - alert: TelegrafHighCPUUsage
        expr: 'cpu_usage_user{cpu="cpu-total"} + cpu_usage_system{cpu="cpu-total"} > 80'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage (Telegraf)"
          description: "CPU usage is above 80% for more than 5 minutes (measured by Telegraf)."
          
      - alert: TelegrafHighMemoryUsage
        expr: 'mem_used_percent > 85'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage (Telegraf)"
          description: "Memory usage is above 85% for more than 5 minutes (measured by Telegraf)."
          
      - alert: TelegrafHighDiskUsage
        expr: 'disk_used_percent{path="/"} > 85'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage (Telegraf)"
          description: "Disk usage is above 85% for more than 5 minutes (measured by Telegraf)."
          
      - alert: TelegrafContainerHighCPU
        expr: 'docker_container_cpu_usage_percent > 90'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container high CPU usage"
          description: "Docker container {{ $labels.container_name }} CPU usage is above 90% for more than 5 minutes."
          
      - alert: TelegrafContainerHighMemory
        expr: 'docker_container_mem_usage_percent > 90'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container high memory usage"
          description: "Docker container {{ $labels.container_name }} memory usage is above 90% for more than 5 minutes."