global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - prometheus-alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nautobot'
    static_configs:
      - targets: ['nautobot:8000']
    metrics_path: /metrics
    
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
      
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']